### ISSUE TITLE
Can't open file that is not encrypted

### ISSUE THREAD

**Issue by ThumNet** [ShipitSmarter/vscode-sops-edit#2]
Trying to open a .enc.yaml file that has not yet been encrypted, results in strange behavior.

![image](https://user-images.githubusercontent.com/692308/213436147-cfefbcb2-7fcf-4881-bc02-ce499e395285.png)

And the .tmp.yaml file is empty
![image](https://user-images.githubusercontent.com/692308/213436547-452d9f65-cf50-4320-a525-5593aea81733.png)

**Comment by bvanderhorn** [comment]
Fixed, and some other bugs as well (sshhh!!)
