### ISSUE TITLE
Decrypt 'removes' diff screen while comitting

### ISSUE THREAD

**Issue by sunib** [ShipitSmarter/vscode-sops-edit#7]
Could the sops extensions keep out of the git commit screen? At the moment that you click the file to get a diff then it's decrypted and then the diff 'jumps' away.

![image](https://github.com/ShipitSmarter/vscode-sops-edit/assets/1828380/fa8517d7-5ac8-4798-9893-6af27b11088b)

**Comment by bvanderhorn** [comment]
resolved
